# Generated by Django 4.2 on 2026-04-03 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100)),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('session_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bio', models.CharField(blank=True, max_length=250)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'Trainer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
