# Generated by Django 4.2 on 2026-04-05 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.CharField(choices=[('1 Week', '1 Week'), ('1 Month', '1 Month'), ('3 Months', '3 Months')], default='1 Month', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift_name',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Day', 'Day'), ('Evening', 'Evening')], default='Morning', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('trainer', 'shift_name')},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_week',
        ),
    ]
