# Generated by Django 4.2 on 2026-04-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subs_status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], default='Active', max_length=20),
        ),
    ]
