# Generated by Django 4.2 on 2026-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_subscription_subs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='hold_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
