# Generated by Django 4.2 on 2026-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('Trainer', 'Trainer'), ('Admin', 'Admin')], default='Member', max_length=20),
        ),
    ]
